language: go

go:
  - 1.9

script:
  - go test -v

before_deploy:
  - go get -u github.com/laher/goxc
  - go get -u github.com/tcnksm/ghr
  - cd vt-cli
  - goxc -pv=$TRAVIS_TAG

deploy:
  provider: script
  script: ghr --username er28-0652 --token $GITHUB_TOKEN --replace --debug $(git tag -l --contains HEAD) ${TRAVIS_TAG} dist/${TRAVIS_TAG}
  skip_cleanup: true
  on:
    tags: true